version: '2.3'
services:
  threeweather:
    image: onlytailei/carla_cil:pytorch1.0-cuda10-oepcv3.4.3-imgaug
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=3
    volumes:
      - /path/to/dataset:/home/dataset
      - /path/to/this_repo/carla_cil_training:/home/ws/carla_cil_training
    working_dir: /home/ws/carla_cil_training
    cpu_count: 24
    mem_reservation: 10000M
    shm_size: 10000M
    command:
      python main.py
      --batch-size 1000
      --workers 24
      --speed-weight 1
      --learning-rate 0.0001
      --lr-gamma 0.5
      --lr-step 10
      --train-dir "/home/dataset/carla_cil/chosen_weather_train/three_train/"
      --eval-dir "/home/dataset/carla_cil/chosen_weather_test/three_test/"
      --net-structure 2
      --gpu 0
      --id three_policy_0137

